### ISSUE TITLE
File format error

### ISSUE THREAD

**Issue by jerviscui** [ramisedhom/obsidian-plugins-categorization#3]
https://github.com/ramisedhom/obsidian-plugins-categorization/blob/main/plugins.md
![image](https://user-images.githubusercontent.com/6396748/198872117-68821266-5515-4485-bb79-e4ac63812d5b.png)

**Comment by ramisedhom** [comment]
Thanks @jerviscui for bringing this up. I'll check this issue.

**Comment by ramisedhom** [comment]
Since the repo had changed from Airtable to [Seatable](https://link.ramisedhom.com/Obsidian-Plugins-Categorization). This bug wouldn't be fixed. Actually the script that generate the markdown file need to be re-developed again. Hence I'm closing this issue for now. If this markdown file is needed, please open a discussion first to discuss its importance.
